AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Search Microservice SAM Template

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 256
    CodeUri: ../../
    Environment:
      Variables:
        DOCUMENTS_TABLE: !ImportValue SynkDocs-DocumentsTable

x-search-policies: &search-policies
  - Statement:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:Query
          - dynamodb:Scan
        Resource:
          - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/SynkDocs-*'
          - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/SynkDocs-*/index/*'

Resources:
  SearchDocumentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/searchservice/functions/searchDocuments/index.handler
      Policies: *search-policies
      Events:
        SearchDocsApi:
          Type: Api
          Properties:
            Path: /documents/search
            Method: get

  RecentDocumentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/searchservice/functions/recentDocuments/index.handler
      Policies: *search-policies
      Events:
        RecentDocsApi:
          Type: Api
          Properties:
            Path: /documents/recent
            Method: get

  StarredDocumentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/searchservice/functions/starredDocuments/index.handler
      Policies: *search-policies
      Events:
        StarredDocsApi:
          Type: Api
          Properties:
            Path: /documents/starred
            Method: get
