AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: User Microservice SAM Template

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 256
    CodeUri: ../../
    Environment:
      Variables:
        USERS_TABLE: !ImportValue SynkDocs-UsersTable
        AVATARS_BUCKET_NAME: synkdocs-user-avatars

Resources:
  GetProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/userservice/functions/getProfile/index.handler
      Events:
        GetProfileApi:
          Type: Api
          Properties:
            Path: /profile
            Method: get

  UpdateProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/userservice/functions/updateProfile/index.handler
      Events:
        UpdateProfileApi:
          Type: Api
          Properties:
            Path: /profile
            Method: put

  UploadAvatarFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/userservice/functions/uploadAvatar/index.handler
      Events:
        UploadAvatarApi:
          Type: Api
          Properties:
            Path: /profile/avatar
            Method: post

  DeleteAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/userservice/functions/deleteAccount/index.handler
      Events:
        DeleteAccountApi:
          Type: Api
          Properties:
            Path: /profile
            Method: delete
