AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: EventBridge Event Bus for SynkDocs Asynchronous Architecture

Resources:
  SynkDocsEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub 'SynkDocs-EventBus-${AWS::StackName}'

Outputs:
  EventBusName:
    Value: !Ref SynkDocsEventBus
  EventBusArn:
    Value: !GetAtt SynkDocsEventBus.Arn
