AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Auth Microservice SAM Template

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 256
    Environment:
      Variables:
        USERS_TABLE: !ImportValue SynkDocs-UsersTable
        EVENT_BUS_NAME: !ImportValue SynkDocs-EventBusName
        JWT_SECRET: synkdocs_dev_secret_key

Resources:
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/register/
      Handler: index.handler
      Events:
        RegisterApi:
          Type: Api
          Properties:
            Path: /register
            Method: post

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/login/
      Handler: index.handler
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /login
            Method: post

  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/logout/
      Handler: index.handler
      Events:
        LogoutApi:
          Type: Api
          Properties:
            Path: /logout
            Method: post

  RefreshTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/refreshToken/
      Handler: index.handler
      Events:
        RefreshTokenApi:
          Type: Api
          Properties:
            Path: /refresh-token
            Method: post

  VerifyTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/verifyToken/
      Handler: index.handler
      Events:
        VerifyTokenApi:
          Type: Api
          Properties:
            Path: /verify-token
            Method: post

  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/health/
      Handler: index.handler
      Events:
        HealthApi:
          Type: Api
          Properties:
            Path: /health
            Method: get

